name: Auto-approve Dependabot PRs

on: pull_request

permissions: { }

jobs:
  dependabot:
    uses: tacascer-org/actions-workflows/.github/workflows/approve_dependabot.yml@v0.5.2
    permissions:
      pull-requests: write
      contents: write
